version: '3.4'

services:
  lidarr-deemix:
    image: itsnebulalol/lidarr-demix
    build:
      context: .
    ports:
      - "8686:8686" # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - ./tmp/config:/config
      - ./tmp/config_deemix:/config_deemix
      - ./tmp/downloads:/downloads
      - ./tmp/music:/music
    restart: always
